### ISSUE TITLE
astool generator: add file path flag

### ISSUE THREAD

**Issue by gedw99** [go-fed/activity#106]
can we make the astool have an extra flag to tell it what folder to gen into ?

at the moment is uses the directory from which the process is started from.

**Comment by cjslep** [comment]
Should be done in both:
87e56d8d962934b0f4b1cadf0c75d1de5ac5d88f
and
5d598046c248105e56c55dcdd67a52eea51d2622

Note that a destination directory is now required, it must be a relative path, and it cannot contain `..` (up a directory) in the path.
