### ISSUE TITLE
Remove `go vet` files and support modules instead

### ISSUE THREAD

**Issue by cjslep** [go-fed/activity#108]
The current `go.mod` file and others are from when `go vet` was supposed to be "the thing".

**Comment by cjslep** [comment]
I thought supporting modules would be as simple an affair as...
823ab4cc5a22bb2e691b49e52edf2634c2686bb2

... but it seems not. :(

**Comment by BenLubar** [comment]
I've been using Go modules with Ravenvale and it's been fine so far.

I'd recommend running `go mod tidy` if you want to remove unused version hashes, and other than that it's fine already.

**Comment by cjslep** [comment]
Alright, I ran `go mod tidy`!
