### ISSUE TITLE
Generate to multiple files

### ISSUE THREAD

**Issue by 21stio** [go-fed/activity#29]
Hey,

can you generate multiple smaller files than rather than having a huge one? Github wont render it and my IDE goland would go totally crazy when Id try to open it.

**Comment by 21stio** [comment]
Im not a hundred percent certain, but I think the go compiler will even just compile the referenced files rather than all struct definitions

**Comment by cjslep** [comment]
Thanks, sounds like a good idea for after v0.1!

Note though that I'm unsure about the partial-compilation of source files. My understanding is that `go install` will have the compiler compile the complete static libraries (all source files), and the linker will only link to the specific symbols it needs in the result.

**Comment by 21stio** [comment]
Cool, thanks for considering :)

Ah okay interesting.. I'll have another look

**Comment by cjslep** [comment]
The following two commits now permit `vocab` and `streams` to output to 1 file per type, as well as a package-wide autogenerated file.

f155f0a3d0e31a58ab5ca5fe1342f0334f13391a
b1609bd71aea298347877518eedc33bcf0915fde

Additionally, all files that are autogenerated how have `gen_` prepended to them, to easily discern what files would be overwritten in a call to `go generate`.

Hope this helps you and others explore this package more!
