### ISSUE TITLE
The AnnouceType interface is not sane

### ISSUE THREAD

**Issue by riking** [go-fed/activity#55]
https://github.com/go-fed/activity/blob/af5ed41/vocab/gen_announce.go

This is the only part of the code I've looked at so far, but I can already tell you this is not the proper way to do anything. For one, the vtables generated for this type will be obnoxiously big, but also the API is impossible to use.

It should look more like `activity.GetObjectList("actor")` or `activity.GetString(JoinContext("http://ostatus.org#", "atomUri")`.

Instead of:

```
if activity.IsReplies() {
  r := activity.GetReplies()
}
```

client code should instead look something like this:

```
if r := activity.GetObject(fed.Join("https://www.w3.org/ns/activitystreams#", "replies")); r != nil {
  replies := fed.ToCollection(r) // returns nil if type is not fed.TypeActivityStreamsCollection / Join(PrefixActiviyStreams, "Collection")

}
```
This interface preserves flexibility to work with new object types without having to re-run code generation.

**Comment by cjslep** [comment]
Good suggestions to consider for the API redesign for v1. You are right that the large vtable is partially why the binary is quite bloated in the v0 design.

However, how would a client be expected to determine the difference between not-present and not-correct-type if `nil` is being returned in both cases? In my mind nil suffers from the same problems as null in other languages in that it is not clear it actually means "not present" and is the reason Optional types exist in other languages, but that requires generics or more code generated structs. I also am not a fan of returning an error in this use case, as I am not sure "wrong type" is an error (but could be convinced it is). This is why the `streams` package is designed the way it is.

Furthermore, how would an API client know which magic string properties to use with which getter? It is not immediately clear to me that passing a string like `"closed"` to one of `GetBool`/`GetTime`/`GetObject`/`GetLink`/`GetSlice` is correct but `"object"` would only be correct for a subset of those. At least with explicit function names, it is immediately clear what forms a property can take without having to consult and master the specification.

I promise you that the choices I made in the v0 design are deliberate and rational, but I concede they were made in a vacuum. Hence why I am very open to feedback (See #48). I also promise you that it is possible to use the API. They may not be the same choices you would have made, so please spare me any further judgmental commentary in the future.

**Comment by cjslep** [comment]
Also note that the API redesign I have tentatively broken out in issue #50.

Finally, I also want to note that most of the interface types are unnecessary, as only some of the Object, Collection, and Link types are needed. The rest require `type` property inspection since a lot of the interfaces are equivalent. I should plan to remove these in 0.2.0, and if I don't have a task for that broken out I will make one.

In general though, people should be sticking to the actual struct types.

**Comment by riking** [comment]
> It is not immediately clear to me that passing a string like "closed" to one of GetBool/GetTime/GetObject/GetLink/GetSlice is correct but "object" would only be correct for a subset of those.

Eh, make a non-qualified match always available but encourage use of the fully `@context` qualified names. That way, your code won't randomly break when using it on a different ActivityPub server.

**Comment by cjslep** [comment]
With the [go-fed](https://go-fed.org) site live now, hopefully the API for properties is better-explained, even if the resulting quantity of methods is mind-numbingly long.

I am not sure if there's anything else that needs to be done for this issue. If there's no further concrete actions and the issue stays quiet, I will close it out in 7 days time (30 days of inactivity).
