### ISSUE TITLE
Use least width integers when possible

### ISSUE THREAD

**Issue by tuxether** [go-fed/activity#70]
Minor nitpick. `pub.RWType` currently has type int. Since there are only two possible values, a bool should suffice.

https://github.com/go-fed/activity/blob/96c9afee84f8e55630c060a436a94de2032efd7f/pub/interfaces.go#L111

Similarly, `pub.FollowResponse` can be uint8 instead of int.

https://github.com/go-fed/activity/blob/96c9afee84f8e55630c060a436a94de2032efd7f/pub/interfaces.go#L209

**Comment by cjslep** [comment]
46d55732d58eec077aaf569fe102acc064ef52b2
